# Perfil de desarrollo: se activa con  -Dspring-boot.run.profiles=dev

# Además de las migraciones reales, carga los datos de prueba
spring.flyway.locations=classpath:db/migration,classpath:db/seed-dev

# Muestra en consola las consultas SQL que ejecuta Hibernate
logging.level.org.hibernate.SQL=debug
